### ISSUE TITLE
Time for authentication 

### ISSUE THREAD

**Issue by SharksT** [ocboogie/authful-actix-web#2]
Why takes so long to authenticate? it is something to do with the session cryptography?

**Comment by ocboogie** [comment]
Authentication must be slow to be safe. Although, it might not have to be *this* slow. In [argonautica](https://github.com/bcmyers/argonautica)'s docs, which is what I'm using  for password hashing, it says:

> If you are using this library to hash user passwords for storage in a database, it is recommended that you adjust these settings for your machine (primarily iterations, and memory_size) until the time it takes to hash a password is approximately 300-500 milliseconds.

You can read more about it [here](https://auth0.com/blog/hashing-passwords-one-way-road-to-security/#No-Need-for-Speed) and [here](https://codahale.com/how-to-safely-store-a-password/).

**Comment by ocboogie** [comment]
Authentication must be slow to be safe. Although, it might not have to be *this* slow. In [argonautica](https://github.com/bcmyers/argonautica)'s docs, which is what I'm using  for password hashing, it says:

> If you are using this library to hash user passwords for storage in a database, it is recommended that you adjust these settings for your machine (primarily iterations, and memory_size) until the time it takes to hash a password is approximately 300-500 milliseconds.

This can be found [here](https://docs.rs/argonautica/0.2.0/argonautica/struct.Hasher.html#method.new).

At some point I'll make the settings for the hasher configurable through environment variables.

You can read more about why hashing must be slow [here](https://auth0.com/blog/hashing-passwords-one-way-road-to-security/#No-Need-for-Speed) and [here](https://codahale.com/how-to-safely-store-a-password/).

**Comment by ocboogie** [comment]
That time is now: https://github.com/ocboogie/authful-actix-web/commit/ac682968041147f7232e331463f39e0b8af01b99. You can configure it with the following variables: `HASHING_ITERATIONS` and  `HASHING_MEMORY_SIZE`. You can read about what these mean [here](https://docs.rs/argonautica/0.2.0/argonautica/index.html#configuration).

**Comment by SharksT** [comment]
Got it, but in the Argonia site they say that the defaults are fast in a MacBook air from 2014, mine is a MacBook pro from 2015, why takes longer (about 2 seconds) to do the same as their MacBook air do in about 300-500ms?

**Comment by SharksT** [comment]
With --release flag it runs in less than 500ms as it should be.
